export const SET_SUBJECT_SELECTED = "SET_SUBJECT_SELECTED";
export const SET_GRADE_SELECTED = "SET_GRADE_SELECTED";

const initialState = {
  students: [
    {
      rollNo: 1,
      section: "",
      gender: "",
      name: "Rithik",
      sub1: 75,
      sub2: 80,
      sub3: 85,
      sub4: 90,
      sub5: 95,
      avg: 80,
    },
    {
      rollNo: 2,
      name: "Abishek",
      sub1: 65,
      sub2: 70,
      sub3: 75,
      sub4: 80,
      sub5: 75,
      avg: 75,
    },
    {
      rollNo: 3,
      name: "Anushka",
      sub1: 78,
      sub2: 89,
      sub3: 76,
      sub4: 56,
      sub5: 71,
      avg: 72,
    },
    {
      rollNo: 4,
      name: "Deepika",
      sub1: 80,
      sub2: 85,
      sub3: 90,
      sub4: 95,
      sub5: 90,
      avg: 90,
    },
    {
      rollNo: 5,
      name: "Harrish",
      sub1: 65,
      sub2: 80,
      sub3: 78,
      sub4: 84,
      sub5: 76,
      avg: 76,
    },
  ],
  grades: [
    {
      grade: 1,
      strength: 60,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Trisha",
    },
    {
      grade: 2,
      strength: 50,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Hansika",
    },
    {
      grade: 3,
      strength: 55,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Swetha",
    },
    {
      grade: 4,
      strength: 45,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Priya",
    },
    {
      grade: 5,
      strength: 50,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Sathya",
    },
    {
      grade: 6,
      strength: 50,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Mani",
    },
    {
      grade: 7,
      strength: 60,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Rahul",
    },
    {
      grade: 8,
      strength: 60,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "John",
    },
    {
      grade: 9,
      strength: 50,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Paul",
    },
    {
      grade: 10,
      strength: 60,
      sub1: "Hindi",
      sub2: "English",
      sub3: "Maths",
      sub4: "Science",
      sub5: "Social",
      staff: "Thomas",
    },
    {
      grade: 11,
      strength: 60,
      sub1: "English",
      sub2: "Computer Science",
      sub3: "Physics",
      sub4: "Chemistry",
      sub5: "Maths",
      staff: "Edward",
    },
    {
      grade: 12,
      strength: 60,
      sub1: "English",
      sub2: "Computer Science",
      sub3: "Physics",
      sub4: "chemistry",
      sub5: "Maths",
      staff: "Ajay Agarwal",
    },
  ],
  schools: [
    {
      id: 0,
      school: "Don Bosco",
      strength: 360,
      district: "North",
      average: 78,
      passPercentage: 81,
      failPercentage: 19,
    },
    {
      id: 1,
      school: "Burul Public School",
      strength: 411,
      district: "South",
      average: 81,
      passPercentage: 82,
      failPercentage: 18,
    },
    {
      id: 2,
      school: "Holy Cross School",
      strength: 650,
      district: "East",
      average: 76,
      passPercentage: 62,
      failPercentage: 38,
    },
    {
      id: 3,
      school: "Green Dale School",
      strength: 720,
      district: "West",
      average: 85,
      passPercentage: 79,
      failPercentage: 21,
    },
    {
      id: 4,
      school: "Tendong Educational Institution",
      strength: 220,
      district: "South",
      average: 87,
      passPercentage: 82,
      failPercentage: 18,
    },
    {
      id: 5,
      school: "Nobel English School",
      strength: 211,
      district: "West",
      average: 65,
      passPercentage: 60,
      failPercentage: 40,
    },
  ],
  lastUpdatedTime: null,
  subjectWise: [
    { name: "English", Highest: 91, Lowest: 21, Average: 57 },
    { name: "Maths", Highest: 53, Lowest: 22, Average: 37 },
    { name: "Hindi", Highest: 91, Lowest: 72, Average: 88 },
    { name: "Social", Highest: 71, Lowest: 42, Average: 52 },
    { name: "Science", Highest: 81, Lowest: 4, Average: 23 },
  ],
  examWise: [
    { name: "Quarterly", Average: 345 },
    { name: "Internal I", Average: 380 },
    { name: "Half Yearly", Average: 327 },
    { name: "Internal II", Average: 403 },
    { name: "Annual", Average: 420 },
  ],
  studentSubjectPerformance: [
    { subject: "English", A: 79, fullMark: 150 },
    { subject: "Maths", A: 98, fullMark: 150 },
    { subject: "Hindi", A: 86, fullMark: 150 },
    { subject: "Science", A: 79, fullMark: 150 },
    { subject: "Social", A: 85, fullMark: 150 },
  ],
  examImprovement: [
    { name: "Quarterly", Average: 4000 },
    { name: "Internal I", Average: 2780 },
    { name: "Half Yearly", Average: 3000 },
    { name: "Internal II", Average: 1890 },
    { name: "Annual", Average: 2000 },
  ],
  subjectWisePass: [
    { name: "Pass", value: 70 },
    { name: "Fail", value: 25 },
    { name: "Absentees", value: 5 },
  ],
  gradeWiseDist: [
    { class: "1", Strength: 4000 },
    { class: "2", Strength: 3000 },
    { class: "3", Strength: 3000 },
    { class: "4", Strength: 3000 },
    { class: "5", Strength: 3000 },
    { class: "6", Strength: 3000 },
    { class: "7", Strength: 2000 },
    { class: "8", Strength: 2780 },
    { class: "9", Strength: 1890 },
    { class: "10", Strength: 2390 },
    { class: "11", Strength: 3490 },
    { class: "12", Strength: 3490 },
  ],
  gradeSelected: null,
  currentSchool: "",
  subjectSelected: null,
};

const reportReducer = (state = initialState, action) => {
  switch (action.type) {
    case SET_SUBJECT_SELECTED:
      return {
        ...state,
        subjectSelected: action.payload,
      };
    case SET_GRADE_SELECTED:
      return {
        ...state,
        gradeSelected: action.payload,
      };
    default:
      return state;
  }
};

export default reportReducer;
